trigger:
  branches:
    include:
      - main

variables:
  buildConfiguration: 'Release'
  releaseBranchName: 'release'

stages:
- stage: 'plan'
  displayName: 'terraform plan'
  jobs: 
  - job: 'plan'
    displayName: 'plan'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'

- stage: 'apply'
  displayName: 'terraform apply'
  jobs: 
  - job: 'plapplyan'
    displayName: 'apply'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'