trigger:
  branches:
    include:
      - main

stages:
  - stage: validate
    jobs:
    - job: validate
      continueOnError: false
      steps:
      - task: TerraformInstaller@0
        displayName: "Install Terraform"
        inputs:
          terraformVersion: '1.5.4'
      - task: TerraformTaskV2@3
        displayName: 'init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'warroyo-se'
          backendAzureRmResourceGroupName: 'tfstate-explore'
          backendAzureRmStorageAccountName: 'tfstate01explore'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'terraform.tfstate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
      - task: TerraformTaskV2@3
        displayName: 'validate'
        inputs:
          provider: 'azurerm'
          command: 'validate'
          
  - stage: plan
    dependsOn: [validate]
    condition: succeeded('validate')
    jobs:
      - job: terraform_plan
        steps:
              - checkout: self
              - task: TerraformInstaller@0
                displayName: 'install'
                inputs:
                  terraformVersion: '1.5.4'
              - task: TerraformTaskV2@3
                displayName: 'init'
                inputs:
                  inputs:
                  provider: 'azurerm'
                  command: 'init'
                  backendServiceArm: 'warroyo-se'
                  backendAzureRmResourceGroupName: 'tfstate-explore'
                  backendAzureRmStorageAccountName: 'tfstate01explore'
                  backendAzureRmContainerName: 'tfstate'
                  backendAzureRmKey: 'terraform.tfstate'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
              - task: TerraformTaskV2@3
                displayName: 'plan'
                inputs:
                  provider: 'azurerm'
                  command: 'plan'
                  # commandOptions: '-input=false -var-file="../vars/$(Environment)/$(Environment).tfvars"'
                  environmentServiceNameAzureRM: 'warroyo-se'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'

  - stage: apply
    dependsOn: [plan]
    condition: succeeded('plan')
    jobs:
      - job: terraform_apply
        steps:
              - checkout: self
              - task: TerraformInstaller@0
                displayName: 'install'
                inputs:
                  terraformVersion: '1.5.4'
              - script: |
                  sudo apt update
                  sudo apt install -y ca-certificates curl gpg
                  sudo mkdir -p /etc/apt/keyrings
                  curl -fsSL https://packages.vmware.com/tools/keys/VMWARE-PACKAGING-GPG-RSA-KEY.pub | sudo gpg --dearmor -o /etc/apt/keyrings/tanzu-archive-keyring.gpg
                  echo "deb [signed-by=/etc/apt/keyrings/tanzu-archive-keyring.gpg] https://storage.googleapis.com/tanzu-cli-os-packages/apt tanzu-cli-jessie main" | sudo tee /etc/apt/sources.list.d/tanzu.list
                  sudo apt update
                  sudo apt install -y tanzu-cli
                displayName: 'tanuz cli'

              - task: TerraformTaskV2@3
                displayName: 'init'
                inputs:
                  inputs:
                  provider: 'azurerm'
                  command: 'init'
                  backendServiceArm: 'warroyo-se'
                  backendAzureRmResourceGroupName: 'tfstate-explore'
                  backendAzureRmStorageAccountName: 'tfstate01explore'
                  backendAzureRmContainerName: 'tfstate'
                  backendAzureRmKey: 'terraform.tfstate'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
              - task: TerraformTaskV2@3
                displayName: 'apply'
                inputs:
                  provider: 'azurerm'
                  command: 'apply'
                  # commandOptions: '-input=false -var-file="../vars/$(Environment)/$(Environment).tfvars"'
                  environmentServiceNameAzureRM: 'warroyo-se'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'